#!/usr/bin/env zsh
#
# Copyright (c) 2010-2014, Benjamin C. Meyer <ben@meyerhome.net>
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
# 3. Neither the name of the project nor the
#    names of its contributors may be used to endorse or promote products
#    derived from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDER ''AS IS'' AND ANY
# EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER BE LIABLE FOR ANY
# DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
# ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#

# Run checks on all files, and keep track of those which were updated
function run_checks {
  # Initialise variables
  local error_message=""
  local php_errors_found=false

  for file in `git diff-index --cached --name-only HEAD` ; do
    if [ -f ${file} ]; then
      if [ "${file:${#1}-4:4}" = ".php" ]; then
        php-cs-fixer fix -vvv --config=/Users/molovo/.files/files/.php_cs ${file} 2>&1 > /dev/null

        if [ $? -ne 0 ]; then
          error_message+="  - ${file}\n"
          php_errors_found=true
        fi
      fi
    fi
  done

  if [ "$php_errors_found" = true ]; then
    echo -en "\n\e[0;33mPHP CS Fixer updated the following files:\e[0;m\n"
    echo -en "${error_message}"
    echo -en "\n\e[0;31mPlease review and commit.\e[0;m\n"
    exit 1
  fi

  exit 0
}

case "${1}" in
  --about )
    echo "Check PHP source files for Coding Standards errors."
    ;;
  * )
    run_checks
    ;;
esac
