#!/usr/bin/env zsh

(( $+functions[fix-elasticsearch-readonly] )) || function fix-elasticsearch-readonly() {
  curl -XPUT -H "Content-Type: application/json" http://localhost:9200/_all/_settings -d '{"index.blocks.read_only_allow_delete": null}'
}
