#!/usr/bin/env zsh

(( $+functions[git-pr-merge] )) || function git-pr-merge() {
  local branch=${$(git status --short --branch -uno --ignore-submodules=all | head -1 | awk '{print $2}' 2>/dev/null)%...*}

  git pr checkout $1
  git rebase -p --autostash $branch

  local pr_branch=$(git pr show $1 --format '%H')
  git checkout $branch
  git merge $pr_branch
}
