#!/usr/bin/env zsh

(( $+functions[restart] )) || function restart() {
  local -a services
  services=("$@")

  if [[ -f '/usr/local/bin/brew' ]]; then
    for service in ${(@f)services[@]}; do
      brew services restart $service
    done
  fi

  if [[ -f '/bin/systemctl' ]]; then
    for service in ${(@f)services[@]}; do
      sudo systemctl $service restart
    done
  fi
}
