#!/usr/bin/env zsh

(( $+functions[scc] )) || function scc() {
  rm -rf var/cache/*
  php bin/console doctrine:cache:clear-query
  php bin/console doctrine:cache:clear-result
  php bin/console doctrine:cache:clear-metadata
  php bin/console cache:pool:clear cache.global_clearer
  php bin/console cache:clear
  php bin/console cache:warmup
}
