#!/usr/bin/env zsh

(( $+functions[stop] )) || function stop() {
  local -a services
  services=("$@")

  if [[ -f '/usr/local/bin/brew' ]]; then
    for service in ${(@f)services[@]}; do
      brew services stop $service
    done
  fi

  if [[ -f '/bin/systemctl' ]]; then
    for service in ${(@f)services[@]}; do
      sudo systemctl $service stop
    done
  fi
}
