#!/usr/bin/env zsh

(( $+functions[tmux] )) || function tmux() {
  if [[ -z $TMUX && ${#@} -eq 0 ]]; then
    if ! command tmux has-session >/dev/null 2>&1; then
      # Create a new session and set terminal overrides,
      # then detach from the session
      command tmux -u new-session \; new-window "tmux set-option -ga terminal-overrides \",$TERM:Tc\"; tmux detach"

      # Create another new session, and this time stay attached
      command tmux -u new-session -s $(whoami)
      return
    fi

    command tmux attach
    return
  fi

  command tmux "$@"
}
