#!/usr/bin/env zsh

(( $+functions[tmux] )) || function tmux() {
  if [[ -z $TMUX && ${#@} -eq 0 ]]; then
    if ! command tmux has-session -t "terminal-override" >/dev/null 2>&1; then
      # Create a new session and set terminal overrides,
      # then detach from the session
      command tmux -u new-session -s "terminal-override" \; new-window "tmux set-option -ga terminal-overrides \",$TERM:Tc\"; tmux detach"
    fi

    if ! command tmux has-session -t "launch" >/dev/null 2>&1; then
      # Create another new session, and this time stay attached
      command tmux -u new-session -s "launch"
      return
    fi

    command tmux attach
    return
  fi

  command tmux "$@"
}
