tap 'caskroom/cask'
tap 'caskroom/versions'
tap 'f/guardian'
tap 'goles/battery'
tap 'hhvm/hhvm'
tap 'homebrew/binary'
tap 'homebrew/bundle'
tap 'homebrew/command-not-found'
tap 'homebrew/completions'
tap 'homebrew/core'
tap 'homebrew/devel-only'
tap 'homebrew/dupes'
tap 'homebrew/nginx'
tap 'homebrew/php'
tap 'homebrew/services'
tap 'homebrew/versions'
tap 'homebrew/x11'
tap 'keplersj/tap'
tap 'neovim/neovim'
tap 'ravenac95/sudolikeaboss'
tap 'sdogruyol/cryload'
tap 'thoughtbot/formulae'
brew 'gdbm'
brew 'openssl'
brew 'readline'
brew 'sqlite'
brew 'xz'
brew 'python3'
brew 'asciinema'
brew 'aspell'
brew 'gettext'
brew 'libffi'
brew 'pcre'
brew 'glib'
brew 'libpng'
brew 'freetype'
brew 'fontconfig'
brew 'pixman'
brew 'cairo'
brew 'git'
brew 'pkg-config'
brew 'gobject-introspection'
brew 'atk'
brew 'autoconf'
brew 'automake'
brew 'bats'
brew 'bdw-gc'
brew 'boost'
brew 'ocaml'
brew 'ocamlbuild'
brew 'camlp4'
brew 'cctools'
brew 'checkbashisms'
brew 'chromedriver', restart_service: true
brew 'clog'
brew 'cmake'
brew 'coreutils'
brew 'gmp'
brew 'libevent'
brew 'libyaml'
brew 'python'
brew 'llvm'
brew 'crystal-lang'
brew 'ctags'
brew 'direnv'
brew 'libgpg-error'
brew 'libassuan'
brew 'libgcrypt'
brew 'libksba'
brew 'pth'
brew 'dirmngr'
brew 'doctl'
brew 'doxygen'
brew 'dwarfutils'
brew 'exercism'
brew 'pcre2'
brew 'fish'
brew 'flex'
brew 'flow'
brew 'fpp'
brew 'freetds'
brew 'fzf'
brew 'mpfr'
brew 'gawk'
brew 'jpeg'
brew 'libtiff'
brew 'webp'
brew 'gd'
brew 'shared-mime-info'
brew 'gdk-pixbuf'
brew 'gem-completion'
brew 'gflags'
brew 'gist'
brew 'git-cal'
brew 'git-extras'
brew 'git-flow'
brew 'git-hooks'
brew 'glew'
brew 'glog'
brew 'gnu-sed'
brew 'pinentry'
brew 'gpg-agent'
brew 'libusb'
brew 'libusb-compat'
brew 'gnupg2'
brew 'go'
brew 'libtool'
brew 'graphicsmagick'
brew 'hicolor-icon-theme'
brew 'icu4c'
brew 'harfbuzz'
brew 'pango'
brew 'gtk+'
brew 'lua'
brew 'highlight'
brew 'htop-osx'
brew 'httpie'
brew 'hub'
brew 'jemalloc'
brew 'oniguruma'
brew 'jq'
brew 'keybase'
brew 'libelf'
brew 'libssh2'
brew 'libgit2'
brew 'memcached'
brew 'libmemcached'
brew 'libogg'
brew 'libpcl'
brew 'libressl'
brew 'libvorbis'
brew 'libxml2'
brew 'libzip'
brew 'lnav'
brew 'sdl2'
brew 'sdl2_image'
brew 'logstalgia'
brew 'luajit'
brew 'lz4'
brew 'makedepend'
brew 'mariadb', restart_service: true
brew 'mas'
brew 'mhash'
brew 'mcrypt'
brew 'md5sha1sum'
brew 's-lang'
brew 'midnight-commander'
brew 'mongodb'
brew 'mycli'
brew 'mysqltuner'
brew 'popt'
brew 'newt'
brew 'openssl@1.1'
brew 'nginx', args: ['devel', 'with-http2'], restart_service: true
brew 'node'
brew 'perl'
brew 'pinentry-mac'
brew 'potrace'
brew 're2c'
brew 'reattach-to-user-namespace'
brew 'redis', restart_service: true
brew 'ruby'
brew 'selenium-server-standalone', restart_service: true
brew 'shellcheck'
brew 'siege'
brew 'spark'
brew 'sphinx-doc'
brew 'stormssh'
brew 'stormssh-completion'
brew 'tbb'
brew 'terminal-notifier'
brew 'the_silver_searcher'
brew 'thefuck'
brew 'tintin'
brew 'tmux'
brew 'unar'
brew 'unixodbc'
brew 'utf8proc'
brew 'v'
brew 'vagrant-completion'
brew 'vim'
brew 'watson'
brew 'wget'
brew 'yarn'
brew 'z'
brew 'zsh'
brew 'f/guardian/guardian'
brew 'goles/battery/battery'
brew 'homebrew/dupes/rsync'
brew 'homebrew/dupes/zlib'
brew 'homebrew/php/php70'
brew 'homebrew/php/composer'
brew 'homebrew/php/igbinary'
brew 'homebrew/php/php-code-sniffer'
brew 'homebrew/php/php-cs-fixer'
brew 'homebrew/php/php54'
brew 'homebrew/php/php54-igbinary'
brew 'homebrew/php/php54-intl'
brew 'homebrew/php/php54-mcrypt'
brew 'homebrew/php/php54-memcached'
brew 'homebrew/php/php54-redis'
brew 'homebrew/php/php54-xdebug'
brew 'homebrew/php/php54-xhprof'
brew 'homebrew/php/php54-yaml'
brew 'homebrew/php/php55'
brew 'homebrew/php/php55-igbinary'
brew 'homebrew/php/php55-intl'
brew 'homebrew/php/php55-mcrypt'
brew 'homebrew/php/php55-memcached'
brew 'homebrew/php/php55-redis'
brew 'homebrew/php/php55-xdebug'
brew 'homebrew/php/php55-xhprof'
brew 'homebrew/php/php55-yaml'
brew 'homebrew/php/php56'
brew 'homebrew/php/php56-igbinary'
brew 'homebrew/php/php56-intl'
brew 'homebrew/php/php56-mcrypt'
brew 'homebrew/php/php56-memcached'
brew 'homebrew/php/php56-redis'
brew 'homebrew/php/php56-xdebug'
brew 'homebrew/php/php56-xhprof'
brew 'homebrew/php/php56-yaml'
brew 'homebrew/php/php70-igbinary', args: ['HEAD']
brew 'homebrew/php/php70-intl'
brew 'homebrew/php/php70-mcrypt'
brew 'homebrew/php/php70-memcached', args: ['HEAD']
brew 'homebrew/php/php70-redis'
brew 'homebrew/php/php70-xdebug'
brew 'homebrew/php/php70-yaml', args: ['HEAD']
brew 'homebrew/php/php71'
brew 'homebrew/php/php71-intl'
brew 'homebrew/php/php71-mcrypt'
brew 'homebrew/php/php71-redis'
brew 'homebrew/php/php71-xdebug'
brew 'homebrew/php/php71-yaml'
brew 'homebrew/php/phpdocumentor'
brew 'homebrew/php/phpunit'
brew 'homebrew/php/pickle'
brew 'homebrew/versions/bison27'
brew 'keplersj/tap/update'
brew 'ravenac95/sudolikeaboss/sudolikeaboss'
brew 'sdogruyol/cryload/cryload'
cask 'anatine'
cask 'betterzipql'
cask 'hyper'
cask 'insomnia'
cask 'java'
cask 'kap'
cask 'keybase'
cask 'qlcolorcode'
cask 'qlimagesize'
cask 'qlmarkdown'
cask 'qlprettypatch'
cask 'qlstephen'
cask 'quicklook-csv'
cask 'quicklook-json'
cask 'raindropio'
cask 'slack-beta'
cask 'suspicious-package'
cask 'vagrant'
cask 'vagrant-manager'
cask 'virtualbox'
cask 'webpquicklook'
mas 'QuickShot', id: 965442961
mas 'Expressions', id: 913158085
mas 'GIFHunter', id: 1031163338
mas 'iA Writer', id: 775737590
mas 'Helium', id: 1054607607
mas 'Keynote', id: 409183694
mas 'Duo', id: 777886035
mas 'Rested', id: 421879749
mas 'Caffeine', id: 411246225
mas 'The Unarchiver', id: 425424353
mas 'CCMenu', id: 603117688
mas 'Boom', id: 415312377
mas 'Pixelmator', id: 407963104
mas 'Tweetbot', id: 557168941
mas 'Numbers', id: 409203825
mas 'Xcode', id: 497799835
mas 'Characters', id: 536511979
mas 'Pages', id: 409201541
mas 'Wunderlist', id: 410628904
mas 'Transmit', id: 403388562
mas 'Reeder', id: 880001334
mas 'Raindrop.io', id: 957810159
mas 'Spark', id: 1176895641
mas 'Paste', id: 967805235
mas 'Sketch', id: 402476602
mas 'Slack', id: 803453959
mas 'Affinity Designer', id: 824171161
