# -*- mode: ruby -*-
# vi: set ft=ruby :

boxes = [
  {
    :name => "xenial",
    :version => "16.04",
    :box => "unbuntu/xenial64",
    :do_image => "ubuntu-16-04-x64"
  }, {
    :name => "wily",
    :version => "15.10",
    :box => "ubuntu/wily64",
    :do_image => "ubuntu-15-10-x64"
  }, {
    :name => "vivid",
    :version => "15.04",
    :box => "ubuntu/vivid64",
    :do_image => "ubuntu-15-04-x64"
  }, {
    :name => "utopic",
    :version => "14.10",
    :box => "ubuntu/utopic64",
    :do_image => "ubuntu-14-10-x64"
  }, {
    :name => "trusty",
    :version => "14.04",
    :box => "ubuntu/trusty64",
    :do_image => "ubuntu-14-04-x64"
  }
]

Vagrant.configure("2") do |config|
  port = 8000
  boxes.each do |box|
    config.vm.define box[:name], autostart: false do |machine|
      machine.vm.hostname = box[:name]
      machine.vm.network :forwarded_port, guest: 80, host: port
      machine.ssh.insert_key = true

      machine.vm.provider :virtualbox do |vb, override|
        override.vm.box = box[:box]
        vb.gui = false
        vb.memory = "1024"
      end
    end

    port += 1
  end
  config.vm.box = "ubuntu/xenial64"
end
